// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtSC40Im8cI_LXh7A9DExBAxFCEKmjGwk',
    appId: '1:463631792568:web:9c740931f0733f37d6f74d',
    messagingSenderId: '463631792568',
    projectId: 'fan-chat-a3fba',
    authDomain: 'fan-chat-a3fba.firebaseapp.com',
    storageBucket: 'fan-chat-a3fba.appspot.com',
    measurementId: 'G-0R4S43SZ4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT09HDqJEDUSM4EKwBDzaV7Sa8r7UkveM',
    appId: '1:463631792568:android:63b02c68522c6333d6f74d',
    messagingSenderId: '463631792568',
    projectId: 'fan-chat-a3fba',
    storageBucket: 'fan-chat-a3fba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzBDPAH_EoA5Zguf3UpYzNm6N3XHLxP5I',
    appId: '1:463631792568:ios:5f7fb81e04ce5edcd6f74d',
    messagingSenderId: '463631792568',
    projectId: 'fan-chat-a3fba',
    storageBucket: 'fan-chat-a3fba.appspot.com',
    iosClientId: '463631792568-46qdckg2nrela7cfpbfo3tka7g7u5kmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fanChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzBDPAH_EoA5Zguf3UpYzNm6N3XHLxP5I',
    appId: '1:463631792568:ios:637d8bf742aee660d6f74d',
    messagingSenderId: '463631792568',
    projectId: 'fan-chat-a3fba',
    storageBucket: 'fan-chat-a3fba.appspot.com',
    iosClientId: '463631792568-7btvc40ke7dcukits3nglncr5lr8ppvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.fanChat.RunnerTests',
  );
}
